---
- name: Installing Docker, creating Container and installing Webserver inside the same with the Git Installed
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
      become: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
      become: yes

    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        become: yes

    - name: Checking Configuration Status
      debug:
        var: x.failed

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present
      become: yes

    - name: Install Docker Python library
      pip:
        name: docker
        state: present
      become: yes

    - name: Configuring Docker network for webserver
      docker_network:
        name: webserver1_network
        driver: bridge

    - name: Pull a docker image
      docker_image:
        name: httpd
        tag: latest
        source: pull
      register: z
    - name: Checking Pull Status
      debug:
        var: z

    - name: Creating a Persistent Volume Dir
      file:
        path: "/root/pv"
        state: directory

    - name: Copying the HTML code in the Directory
      copy:
        src: "index.html"
        dest: "/root/pv"

    - name: Launching an HTTPD Container
      when: z is defined and z.failed == false
      docker_container:
        name: apache-server-container
        image: httpd
        state: started
        networks:
          - name: webserver1_network
        ports:
          - "8080:80"
        volumes:
          - "/root/pv:/usr/local/apache2/htdocs"
          command: /bin/bash -c "apt-get update && apt-get install -y git && exec httpd -DFOREGROUND"

- name: Clone Git repository
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Install Git
      package:
        name: git
        state: present

    - name: Clone Git repository
      git:
        repo: https://github.com/Ranjithkumar-Mathiazhagan/CA_1
        dest: Ranjithkumar-Mathiazhagan/CA_1


